package com.projects.UrlShortener;

import org.springframework.data.annotation.Id;

public record UrlMapping(@Id String id, String shortCode, String originalUrl) {

    public UrlMapping(String shortCode, String originalUrl) {
        this(null, shortCode, originalUrl);  // null for ID as it is autogenerated
    }
}
